apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cicd-acme
spec:
  encryptedData:
    token: AgB9QufssBqTYggPfMjjpY3n+lfJsL3TUvfzwFMYhepfDt/UPkHsP19pc1DtzPYRGkuBG8NdNWJBzGHOMWustSFwyZzhIhNYUS1Q1zXhWdr1rMRpbprZ2Mb+A9j+SapdmU5qcb6wsdRqbXFlrW6iHYv088xvJYNJmIk7e6y3Qwl6vFS2heSMk1ap7gDM05D0OoZaoBxsbRzrL+P5RqNz+FMNuUPk6zVXYAkyZT6UMHGUI9FIoeHbbgLu2c7A2mC4kYAD6bDwQJ7dNewdhHO+S7hA71bInYXeN4pgk1eJ1TGA+CxUc7eES2vFL6l6a3g62R3CoH8ZfIcE6jNblsK13MkNrNZlgm7bkFbYKbwECFycmcc8zyBGQuUGLlkhDoZodzxlpSd0tXn0GMiORo/4kwBgeSWY5rEW/p9yqS+h88AetDv/3/z+zsG5ywLvQssRPDNu72tFioBYaXGL+4YsAfT4tkxqwPHFaNXr3VPOZgPwhWERFI7SWTAFK4AaVk4Jcv1ZCJ0kW5klzszQk1TD7k6MZD38+Iw5Y7xqMH8b+X3dmvtc/GA0bs6rNsCzxyhJUjRxU3B+0HO0eQF7sH1Djr2vWEmwI1p4+f6bmeC7k0HAEY+H0d0qR713vQX7fEUofr2iG0qinPb8N2ba1+bCu+0Bjhy6AXzpEZlOd8Z2Mf+04NzNs2kgOu5qC/zEVIkW/oNFiN+uNzJktIwLSx1F+4kawvlhEIL5h2klBF3jGZf7uRK5KkZhGyS0
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: cicd-acme

