apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gitops-webhook-token
spec:
  encryptedData:
    webhook-token: AgBTF96QhIyvrPT5fs6RZ9FbnqaLWBx20bZZf7/UQ/+0E1wi+AaYCZM5xwfR1KHOU0z2dLs6GLLq20/XGNLgLOrzruySsXF2lPm3tseSlgx+ld2MewRjZ/Px1FXE0lv3T2/TWKs8OEGnzwSZdJfDWZBduYr2uyyKJrJI4OdDxIDFWO/OceaGFJPy0dHWm5ZVRBuUMOynLvTDN3KMKpAD8ANnVrWMnbUjklXgaRe2T1T0F0jGWzAkMBA06liffn63pXwEcV2je96xHLB+XM252qz+1CRMyN7fU9JIe22IyNaTvtnOKQbn+i7VHgqUPAWBcb332X3/hypyoifeiPPshmm+BHM7q64YNV0iffjjQlHuOoxaHeX8f+tqVD/Kert9teE+1+WGSeR+BucX1RJjiw8P3vYH1h5E3TohouSbNNk7qtWlUFKNgdYyHy7+iApoNzX7GyjF/ny0lyKM8we89+eUl19WEwC+eI/pWgxm2ImVFhQGQTDhJJqO1WTjtq9iBfAnTWL7aMVcRDjJZJJ9j2kmK9AegKB+wn1jiTKH0/XDw+SUi4cUTjKOO5I5k9Fa8RNTDFOHBRTqbMC4zGQCD2eQNFl2xjdwZgVRkSrY+SfHRiPEISE7+eGusmlCNVNj4OShDfnFll90Y7zTo/tQT0n4dX+GWY3EIOy61OfvOd/V1VOLvv36I8G5I4zd0l1AObH1M37tyWsYTJDhMXDCaWNbQD4wIVb6NKpZyb4GoJr8AB9YKiHl0Gxm
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: gitops-webhook-token

