apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: gitops-webhook-token
spec:
  encryptedData:
    webhook-token: AgDVJ9RjaVYBEBPmQ3MkxZvQDBkRgzeV+VOftkY3uBNjKUPaNsKhKhrElaWjYj30HOAxt5mOUgnHv9UULiKoHxoJuLhRt48OUmmBUzHew6zCr4TTIPGFr+50PCnfdhaqCQ7ueYiC9dwjAywiZXaPC7jObSTbLY+PnBRMeoQ1KUD/k7pHynMBBlveQTVpqbwP2dwjFb+Yo4ZMUQ526ns+nf6+OH3v7LX5SOuaFNUS7I3BAxacaki5vKJPkVDVCh7yS+EXKu1vKm4lQ8l9KITXLzMxRJoonxK6UhW0+jGwtDB/zp9f+6ZeKo5iTwytcn+1fS5uUUp9dovPjpBq+zS1ScJwMt/WygpsEP+n1Wcx/VyRy0ro5bVyo4xs6M+jICz5sDIxvHOZMKO/+qTGIyAVtmVQyWZTBuT/n2f3AnU6xRQPswEp2bp0aAMTon6ZOj7kJe0Vn1VWtLd1sDORzvrsBzNmGvmyqrl54xix40DTTQnWKBn/oqIOpFQ6Y8XidHTViNYRMdJ6NtuCkc/xdyG8EyGURCG1Idq+V93qhXXIG5G1Q/rPiUmcGLVteJlPjW4ZTY7z/WXgblV1cLJ8OBbegmVHbvNORAJHEndsYpE7PVJz9NjELu4cbBqRSkth5dYS+f6vSFaEoPmZZ6GZCExRrSv7qZZux71pRBUjEHV641VVZQLnXgNdArsc+0qVTHw3hlUm8FJm3W4VoTLjcA6IrumEcQ0AdnLrrkwSfejcf9pNRH2SceJnR5aN
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: gitops-webhook-token

