apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: create-customer-details-rest
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-APEH-CFZE47
    use: CloudPakForIntegrationProduction
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: '12.0'
  adminServerSecure: true
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/ci/create-customer-details-rest:3927ed28c9ee132ad2f8bf7c896d5059d98856d0
        imagePullPolicy: Always
  configurations:
    - create-customer-serverconf.yaml
    - create-customer-policy
